name: "Feature"
description: "Nova funcionalidade ou melhoria"
body:
  - type: input
    id: objetivo
    attributes:
      label: Objetivo
  - type: textarea
    id: escopo
    attributes:
      label: Escopo
  - type: textarea
    id: criterios
    attributes:
      label: Critérios de aceite
  - type: textarea
    id: notas
    attributes:
      label: Notas adicionais